library(cn.mops)
BAMFiles <- list.files(path="/home/karla/mk-cn.MOPS/data", pattern=".bam$")
segments <- read.table("/home/karla/mk-cn.MOPS/data/bedfile.bed",sep="\t",as.is=TRUE)
gr <- GRanges(segments[,1],IRanges(segments[,2],segments[,3]))
X <- getSegmentReadCountsFromBAM(BAMFiles,GR=gr, mode="paired", BAIFiles=".bai$")
rgresCNMOPS <- exomecn.mops(X)
resCNMOPS <- calcIntegerCopyNumbers(resCNMOPS)
plot(resCNMOPS,which=1)
CNVs <- as.data.frame(cnvs(resCNMOPS))
write.csv(CNVs,file="cnvs.csv")